In [ ]:
pip install langchain

Collecting langchain
  Downloading langchain-0.2.7-py3-none-any.whl (983 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.6/983.6 kB 17.3 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.0.31)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (3.9.5)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (4.0.3)
Collecting langchain-core<0.3.0,>=0.2.12 (from langchain)
  Downloading langchain_core-0.2.17-py3-none-any.whl (366 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.1/366.1 kB 28.5 MB/s eta 0:00:00
Collecting langchain-text-splitters<0.3.0,>=0.2.0 (from langchain)
  Downloading langchain_text_splitters-0.2.2-py3-none-any.whl (25 kB)
Collecting langsmith<0.2.0,>=0.1.17 (from langchain)
  Downloading langsmith-0.1.85-py3-none-any.whl (127 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 kB 17.9 MB/s eta 0:00:00
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (1.25.2)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.8.2)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.31.0)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (8.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.9.4)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.3.0,>=0.2.12->langchain)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.12->langchain) (24.1)
Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.2.0,>=0.1.17->langchain)
  Downloading orjson-3.10.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.1/141.1 kB 18.1 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2024.7.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.0.3)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.12->langchain)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Installing collected packages: orjson, jsonpointer, jsonpatch, langsmith, langchain-core, langchain-text-splitters, langchain
Successfully installed jsonpatch-1.33 jsonpointer-3.0.0 langchain-0.2.7 langchain-core-0.2.17 langchain-text-splitters-0.2.2 langsmith-0.1.85 orjson-3.10.6

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
pip install chromadb

Collecting chromadb
  Downloading chromadb-0.5.4-py3-none-any.whl (581 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 8.0 MB/s eta 0:00:00
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.2.1)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.10/dist-packages (from chromadb) (2.8.2)
Collecting chroma-hnswlib==0.7.5 (from chromadb)
  Downloading chroma_hnswlib-0.7.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 77.4 MB/s eta 0:00:00
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.111.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 13.8 MB/s eta 0:00:00
Collecting uvicorn[standard]>=0.18.3 (from chromadb)
  Downloading uvicorn-0.30.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 9.2 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.0.0,>=1.22.5 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.25.2)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.5.0-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.12.2)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.18.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 94.3 MB/s eta 0:00:00
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.25.0-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 10.6 MB/s eta 0:00:00
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.25.0-py3-none-any.whl (18 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.46b0-py3-none-any.whl (11 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.25.0-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 kB 17.5 MB/s eta 0:00:00
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.19.1)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 10.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (4.66.4)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.4.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.64.1)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.1.3-cp39-abi3-manylinux_2_28_x86_64.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 30.4 MB/s eta 0:00:00
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.12.3)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-30.1.0-py2.py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 53.0 MB/s eta 0:00:00
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.10/dist-packages (from chromadb) (8.5.0)
Requirement already satisfied: PyYAML>=6.0.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.0.1)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-4.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.10/dist-packages (from chromadb) (3.10.6)
Collecting httpx>=0.27.0 (from chromadb)
  Downloading httpx-0.27.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 5.6 MB/s eta 0:00:00
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (24.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (1.1.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (2.0.1)
Collecting starlette<0.38.0,>=0.37.2 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.37.2-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 10.7 MB/s eta 0:00:00
Collecting fastapi-cli>=0.0.2 (from fastapi>=0.95.2->chromadb)
  Downloading fastapi_cli-0.0.4-py3-none-any.whl (9.5 kB)
Requirement already satisfied: jinja2>=2.11.2 in /usr/local/lib/python3.10/dist-packages (from fastapi>=0.95.2->chromadb) (3.1.4)
Collecting python-multipart>=0.0.7 (from fastapi>=0.95.2->chromadb)
  Downloading python_multipart-0.0.9-py3-none-any.whl (22 kB)
Collecting ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 (from fastapi>=0.95.2->chromadb)
  Downloading ujson-5.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 3.4 MB/s eta 0:00:00
Collecting email_validator>=2.0.0 (from fastapi>=0.95.2->chromadb)
  Downloading email_validator-2.2.0-py3-none-any.whl (33 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (2024.7.4)
Collecting httpcore==1.* (from httpx>=0.27.0->chromadb)
  Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 11.3 MB/s eta 0:00:00
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (1.3.1)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.27.0->chromadb)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 9.1 MB/s eta 0:00:00
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.31.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.7)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 5.4 MB/s eta 0:00:00
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (24.3.25)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.0)
Collecting deprecated>=1.2.6 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Collecting importlib-metadata<=7.1,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.63.2)
Collecting opentelemetry-exporter-otlp-proto-common==1.25.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.25.0-py3-none-any.whl (17 kB)
Collecting opentelemetry-proto==1.25.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.25.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 kB 7.8 MB/s eta 0:00:00
Collecting opentelemetry-instrumentation-asgi==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.46b0-py3-none-any.whl (14 kB)
Collecting opentelemetry-instrumentation==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.46b0-py3-none-any.whl (29 kB)
Collecting opentelemetry-semantic-conventions==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.46b0-py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.5/130.5 kB 16.9 MB/s eta 0:00:00
Collecting opentelemetry-util-http==0.46b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.46b0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.46b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (67.7.2)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.46b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.14.1)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.46b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (2.20.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from tokenizers>=0.13.2->chromadb) (0.23.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (13.7.1)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.4/341.4 kB 35.7 MB/s eta 0:00:00
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.19.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 62.8 MB/s eta 0:00:00
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 61.0 MB/s eta 0:00:00
Collecting websockets>=10.4 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 15.5 MB/s eta 0:00:00
Collecting dnspython>=2.0.0 (from email_validator>=2.0.0->fastapi>=0.95.2->chromadb)
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 31.4 MB/s eta 0:00:00
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2023.6.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<=7.1,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.19.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.2->fastapi>=0.95.2->chromadb) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.3.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer>=0.9.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer>=0.9.0->chromadb) (2.16.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx>=0.27.0->chromadb) (1.2.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 12.5 MB/s eta 0:00:00
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.9.0->chromadb) (0.1.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.0)
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... done
  Created wheel for pypika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53725 sha256=c005c0a3701e4f71e624dbb551b037aab0c14ee12611aa7dec1443925722133e
  Stored in directory: /root/.cache/pip/wheels/e1/26/51/d0bffb3d2fd82256676d7ad3003faea3bd6dddc9577af665f4
Successfully built pypika
Installing collected packages: pypika, monotonic, mmh3, websockets, uvloop, ujson, python-multipart, python-dotenv, overrides, opentelemetry-util-http, opentelemetry-proto, importlib-metadata, humanfriendly, httptools, h11, dnspython, deprecated, chroma-hnswlib, bcrypt, backoff, asgiref, watchfiles, uvicorn, starlette, posthog, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, httpcore, email_validator, coloredlogs, opentelemetry-semantic-conventions, opentelemetry-instrumentation, onnxruntime, kubernetes, httpx, opentelemetry-sdk, opentelemetry-instrumentation-asgi, fastapi-cli, opentelemetry-instrumentation-fastapi, opentelemetry-exporter-otlp-proto-grpc, fastapi, chromadb
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 8.0.0
    Uninstalling importlib_metadata-8.0.0:
      Successfully uninstalled importlib_metadata-8.0.0
Successfully installed asgiref-3.8.1 backoff-2.2.1 bcrypt-4.1.3 chroma-hnswlib-0.7.5 chromadb-0.5.4 coloredlogs-15.0.1 deprecated-1.2.14 dnspython-2.6.1 email_validator-2.2.0 fastapi-0.111.0 fastapi-cli-0.0.4 h11-0.14.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.0 humanfriendly-10.0 importlib-metadata-7.1.0 kubernetes-30.1.0 mmh3-4.1.0 monotonic-1.6 onnxruntime-1.18.1 opentelemetry-api-1.25.0 opentelemetry-exporter-otlp-proto-common-1.25.0 opentelemetry-exporter-otlp-proto-grpc-1.25.0 opentelemetry-instrumentation-0.46b0 opentelemetry-instrumentation-asgi-0.46b0 opentelemetry-instrumentation-fastapi-0.46b0 opentelemetry-proto-1.25.0 opentelemetry-sdk-1.25.0 opentelemetry-semantic-conventions-0.46b0 opentelemetry-util-http-0.46b0 overrides-7.7.0 posthog-3.5.0 pypika-0.48.9 python-dotenv-1.0.1 python-multipart-0.0.9 starlette-0.37.2 ujson-5.10.0 uvicorn-0.30.1 uvloop-0.19.0 watchfiles-0.22.0 websockets-12.0

In [ ]:
pip install langchain_community

Collecting langchain_community
  Downloading langchain_community-0.2.7-py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 30.6 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (2.0.31)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (3.9.5)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Requirement already satisfied: langchain<0.3.0,>=0.2.7 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (0.2.7)
Requirement already satisfied: langchain-core<0.3.0,>=0.2.12 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (0.2.17)
Requirement already satisfied: langsmith<0.2.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (0.1.85)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (1.25.2)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (2.31.0)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (8.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (4.0.3)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.21.3-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 8.2 MB/s eta 0:00:00
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Requirement already satisfied: langchain-text-splitters<0.3.0,>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from langchain<0.3.0,>=0.2.7->langchain_community) (0.2.2)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain<0.3.0,>=0.2.7->langchain_community) (2.8.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.12->langchain_community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.12->langchain_community) (24.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.0->langchain_community) (3.10.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain_community) (2024.7.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain_community) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain_community) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.12->langchain_community) (3.0.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain<0.3.0,>=0.2.7->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain<0.3.0,>=0.2.7->langchain_community) (2.20.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: mypy-extensions, marshmallow, typing-inspect, dataclasses-json, langchain_community
Successfully installed dataclasses-json-0.6.7 langchain_community-0.2.7 marshmallow-3.21.3 mypy-extensions-1.0.0 typing-inspect-0.9.0

In [ ]:
#pip install tiktoken==0.5.1

In [ ]:
pip install langchain_openai

Collecting langchain_openai
  Downloading langchain_openai-0.1.16-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: langchain-core<0.3.0,>=0.2.17 in /usr/local/lib/python3.10/dist-packages (from langchain_openai) (0.2.17)
Collecting openai<2.0.0,>=1.32.0 (from langchain_openai)
  Downloading openai-1.35.13-py3-none-any.whl (328 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.5/328.5 kB 12.6 MB/s eta 0:00:00
Collecting tiktoken<1,>=0.7 (from langchain_openai)
  Downloading tiktoken-0.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 68.7 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.17->langchain_openai) (6.0.1)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.17->langchain_openai) (1.33)
Requirement already satisfied: langsmith<0.2.0,>=0.1.75 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.17->langchain_openai) (0.1.85)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.17->langchain_openai) (24.1)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.17->langchain_openai) (2.8.2)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.3.0,>=0.2.17->langchain_openai) (8.5.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.32.0->langchain_openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai<2.0.0,>=1.32.0->langchain_openai) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.32.0->langchain_openai) (0.27.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.32.0->langchain_openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.32.0->langchain_openai) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai<2.0.0,>=1.32.0->langchain_openai) (4.12.2)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from tiktoken<1,>=0.7->langchain_openai) (2024.5.15)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.10/dist-packages (from tiktoken<1,>=0.7->langchain_openai) (2.31.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.32.0->langchain_openai) (3.7)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.32.0->langchain_openai) (1.2.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.32.0->langchain_openai) (2024.7.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.32.0->langchain_openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2.0.0,>=1.32.0->langchain_openai) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.17->langchain_openai) (3.0.0)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.75->langchain-core<0.3.0,>=0.2.17->langchain_openai) (3.10.6)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain-core<0.3.0,>=0.2.17->langchain_openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->langchain-core<0.3.0,>=0.2.17->langchain_openai) (2.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken<1,>=0.7->langchain_openai) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken<1,>=0.7->langchain_openai) (2.0.7)
Installing collected packages: tiktoken, openai, langchain_openai
Successfully installed langchain_openai-0.1.16 openai-1.35.13 tiktoken-0.7.0

In [ ]:
pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence_transformers-3.0.1-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 4.0 MB/s eta 0:00:00
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.41.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.66.4)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (2.3.0+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.25.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.11.4)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.23.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2023.6.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (6.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2.31.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence_transformers) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (1.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.4)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.11.0->sentence_transformers)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence_transformers) (2.3.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence_transformers)
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 68.5 MB/s eta 0:00:00
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (2024.5.15)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.4.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence_transformers) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, sentence_transformers
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.82 nvidia-nvtx-cu12-12.1.105 sentence_transformers-3.0.1

In [ ]:
#pip install chromadb

In [ ]:
# import required modules
import zipfile
import pandas as pd

In [ ]:
df = pd.read_csv('/content/BusinessAnalyst.csv.zip')

# display dataset
df = df.iloc[:,2:]

In [ ]:
len(df)

4092

In [ ]:
df1 = pd.read_csv('/content/DataAnalyst.csv.zip')

# display dataset
df1 = df1.iloc[:,1:]

In [ ]:
df2 = pd.read_csv('/content/DataEngineer.csv.zip')

# display dataset
#df2 = df2.iloc[:,1:]

In [ ]:
df3 = pd.read_csv('/content/DataScientist.csv.zip')

# display dataset
df3 = df3.iloc[:,2:]

In [ ]:
df_new = pd.concat([pd.concat([pd.concat([df,df1],ignore_index=True),df2],ignore_index=True),df3],ignore_index=True)

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12782 entries, 0 to 12781
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          12782 non-null  object
 1   Salary Estimate    12782 non-null  object
 2   Job Description    12782 non-null  object
 3   Rating             12782 non-null  object
 4   Company Name       12781 non-null  object
 5   Location           12782 non-null  object
 6   Headquarters       12782 non-null  object
 7   Size               12782 non-null  object
 8   Founded            12782 non-null  object
 9   Type of ownership  12782 non-null  object
 10  Industry           12782 non-null  object
 11  Sector             12782 non-null  object
 12  Revenue            12782 non-null  object
 13  Competitors        12382 non-null  object
 14  Easy Apply         12382 non-null  object
dtypes: object(15)
memory usage: 1.5+ MB

In [ ]:
df_new.tail()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
12777,AWS Data Engineer,$55K-$112K (Glassdoor est.),About Us\n\nTachyon Technologies is a Digital ...,4.4,Tachyon Technologies\n4.4,"Dublin, OH","Irving, TX",201 to 500 employees,2011,Company - Private,IT Services,Information Technology,$10 to $25 million (USD),-1,-1
12778,Data Analyst â Junior,$55K-$112K (Glassdoor est.),"Job description\nInterpret data, analyze resul...",5.0,"Staffigo Technical Services, LLC\n5.0","Columbus, OH","Woodridge, IL",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
12779,Security Analytics Data Engineer,$55K-$112K (Glassdoor est.),Job DescriptionThe Security Analytics Data Eng...,3.8,"PDS Tech, Inc.\n3.8","Dublin, OH","Irving, TX",5001 to 10000 employees,1977,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),-1,-1
12780,Security Analytics Data Engineer,$55K-$112K (Glassdoor est.),The Security Analytics Data Engineer will inte...,4.0,Data Resource Technologies\n4.0,"Dublin, OH","Omaha, NE",1 to 50 employees,-1,Company - Private,Accounting,Accounting & Legal,Less than $1 million (USD),-1,-1
12781,Patient Safety Physician or Safety Scientist -...,$55K-$112K (Glassdoor est.),"Help us transform patients' lives.\nAt UCB, we...",3.7,UCB\n3.7,"Slough, OH","Brussel, Belgium",5001 to 10000 employees,-1,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),AbbVie,-1

In [ ]:
df_new1 = df_new.copy()

In [ ]:
# split the Name column into two columns
df_new1[['Company Name','Ratings']] = df_new1['Company Name'].str.split('\n',expand=True)

In [ ]:
# split the Name column into two columns
df_new1[['Salary Estimate','website']] = df_new1['Salary Estimate'].str.split('(',expand=True)

In [ ]:
df_new1.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Ratings,website
0,Business Analyst - Clinical & Logistics Platform,$56K-$102K,Company Overview\n\n\nAt Memorial Sloan Ketter...,3.9,Memorial Sloan-Kettering,"New York, NY","New York, NY",10000+ employees,1884,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Mayo Clinic, The Johns Hopkins Hospital, MD An...",-1,3.9,Glassdoor est.)
1,Business Analyst,$56K-$102K,We are seeking for an energetic and collaborat...,3.8,Paine Schwartz Partners,"New York, NY","New York, NY",1 to 50 employees,-1,Company - Private,Venture Capital & Private Equity,Finance,Unknown / Non-Applicable,-1,True,3.8,Glassdoor est.)
2,Data Analyst,$56K-$102K,"For more than a decade, Asembia has been worki...",3.6,Asembia,"Florham Park, NJ","Florham Park, NJ",501 to 1000 employees,2004,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$5 to $10 million (USD),-1,-1,3.6,Glassdoor est.)
3,"Information Security Analyst, Incident Response",$56K-$102K,Job Description Summary\nThe Information Secur...,3.6,BD,"Franklin Lakes, NJ","Franklin Lakes, NJ",10000+ employees,1897,Company - Public,Health Care Products Manufacturing,Manufacturing,$10+ billion (USD),"Abbott, Siemens, Baxter",-1,3.6,Glassdoor est.)
4,Analyst - FP&A Global Revenue,$56K-$102K,Magnite is the world's largest independent sel...,3.4,Rubicon Project,"New York, NY","Los Angeles, CA",201 to 500 employees,2007,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"PubMatic, AppNexus, Index Exchange",True,3.4,Glassdoor est.)

In [ ]:
df_new2 = df_new1.iloc[:,:-3]

In [ ]:
df_new2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12782 entries, 0 to 12781
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          12782 non-null  object
 1   Salary Estimate    12782 non-null  object
 2   Job Description    12782 non-null  object
 3   Rating             12782 non-null  object
 4   Company Name       12781 non-null  object
 5   Location           12782 non-null  object
 6   Headquarters       12782 non-null  object
 7   Size               12782 non-null  object
 8   Founded            12782 non-null  object
 9   Type of ownership  12782 non-null  object
 10  Industry           12782 non-null  object
 11  Sector             12782 non-null  object
 12  Revenue            12782 non-null  object
 13  Competitors        12382 non-null  object
 14  page_content       12782 non-null  object
dtypes: object(15)
memory usage: 1.5+ MB

In [ ]:


# Create page content column
df_new2['page_content'] = "Job Title: " + df_new2['Job Title'] + "\n" + "Salary Estimate: " + df_new2['Salary Estimate'] + "\n" + "Job Description: " +df_new2['Job Description'] + "\n" +"Rating: " + str(df_new2['Rating']) + "\n" + "Company Name: " + df_new2['Company Name'] + "\n" + "Location: " + df_new2['Location'] + "\n" + "Headquarters: " + df_new2['Headquarters'] + "\n" + "Size: " + df_new2['Size'] + "\n" + "Type of ownership: " + df_new2['Type of ownership'] + "\n" + "Industry: " + df_new2['Industry'] + "\n" + "Sector: " + df_new2['Sector'] + "\n" + "Competitors: " + df_new2["Competitors"]

In [ ]:
df_new2['page_content'][0]

"Job Title: Business Analyst - Clinical & Logistics Platform\nSalary Estimate: $56K-$102K \nJob Description: Company Overview\n\n\nAt Memorial Sloan Kettering (MSK), we’re not only changing the way we treat cancer, but also the way the world thinks about it. By working together and pushing forward with innovation and discovery, we’re driving excellence and improving outcomes. For the 28th year, MSK has been named a top hospital for cancer by U.S. News & World Report. We are proud to be on Becker’s Healthcare list as one of the 150 Great Places to Work in Healthcare in 2018, as well as one of Glassdoor’s Employees’ Choice Best Place to Work for 2018. We’re treating cancer, one patient at a time. Join us and make a difference every day.\n\nJob Description\n\n\nWe are excited to recruit two Business Analyst(s) to join our digital, informatics and technology organization who will measure success on our high priority platforms supported by the Division of Health Informatics. DHI focuses on the interaction of people, processes, and technology enabling MSK to meet critical patient care and research objectives. Our division manages a suite of clinical information systems including the electronic health record, ancillary systems and other core components that enable decision support, health information exchange and knowledge management.\n\nAbout the Clinical and Logistics Platform:MSK has committed to transforming itself into a digital organization. To help advance the transformation, MSK has committed to the Scaled Agile Framework (SAFe) as a method of managing technology work. As part of our digital transformation, MSK has identified a set of platforms that it will be creating to advance its digital transformation.\n\nOne of these high priority platforms is the Clinical and Logistics Platform, which is part of MSK’s digital ecosystem. The focus of the Clinical and Logistics Platform is to enable our Care Teams and Health Care Providers with a pre-integrated platform comprising of all our clinical, logistics, and communication systems. We aim to provide a world-class user experience, reduce friction and burnout to our Care Teams, and empower the Care Team members to provide the best patient experience.\n\nYou will:\nSupport agile team in translating end user requirements into set of user product criteria for technical development team & developing documentation\nConnect with team to confirm product commitments\nConduct data analysis and research required for development team to make decisions\nCollaborate with team to understand, analyze, document, and communicate platform requirements\nPartner with key stakeholders to articulate and refine product vision throughout the iteration process\nHelp design team in translating product needs/requirements into deliverable units of work\nAble to synthesize metrics such as: user satisfaction/adoption, quality of products delivered, time-to-market, timely delivery etc.\nCollaborates closely with agile teams to translate business requirements and operational metrics between user groups and developers\nProvide definitions for product criteria, readiness, completeness etc.\nYou have:\n2-4 years of experience in a healthcare setting in a role such as data/business analysis\nBachelor's degree in Health Informatics, Computer Science, Information Systems or related\nSAFe certification or exposure to agile methodologies a strong plus\nStrong problem-solving and analytical skills, with ability to synthesize user needs and pull insights out of data\nExcellent communicator able to negotiate with business to clarify needs vs. wants/likes to balance with development cost and risk\nAbility to break down and describe business needs into work supporting an iterative and incremental delivery model\nCredibility with both business leaders, product designers, & developers\n#LI-POST\n\nBenefits\n\nCompetitive compensation packages | Sick Time | Generous Vacation + 12 holidays to recharge & refuel | Internal Career Mobility & Performance Consulting | Medical, Dental, Vision, FSA & Dependent Care | 403b retirement savings plan match | Tuition Reimbursement | Parental Leave & Adoption Assistance | Commuter Spending Account | Fitness Discounts & Wellness Program | Resource Networks | Life Insurance & Disability | Remote Flexibility\n\nWe believe in communication, transparency, and thinking beyond your 8-hour day @ MSK. It’s important to us that you have a sense of impact, community, and work/life balance to be and feel your best.\n\nOur Hiring Process\n\nYou read the ad, agree it sounds like a great fit & apply -> Talent Acquisition contacts you to schedule a phone interview (if your profile aligns)-> after speaking with the Talent Acquisition Specialist, you will connect with the Hiring Manager by phone or video call -> if your experience is a fit, you will move forward to an on-site visit or video call with the team -> post interview feedback -> ideally an offer! -> reference check & onboarding -> orientation & official welcome to MSK\n\nMSK has been named a Best Place to Work in IT by Insider Pro & Computerworld, for the 2nd year in a row.\n\nWe look forward to meeting soon!\n\nClosing\n\n\nMSK is an equal opportunity and affirmative action employer committed to diversity and inclusion in all aspects of recruiting and employment. All qualified individuals are encouraged to apply and will receive consideration without regard to race, color, gender, gender identity or expression, sexual orientation, national origin, age, religion, creed, disability, veteran status or any other factor which cannot lawfully be used as a basis for an employment decision.\n\nFederal law requires employers to provide reasonable accommodation to qualified individuals with disabilities. Please tell us if you require a reasonable accommodation to apply for a job or to perform your job. Examples of reasonable accommodation include making a change to the application process or work procedures, providing documents in an alternate format, using a sign language interpreter, or using specialized equipment.\nRating: 0        3.9\n1        3.8\n2        3.6\n3        3.6\n4        3.4\n        ... \n12777    4.4\n12778    5.0\n12779    3.8\n12780    4.0\n12781    3.7\nName: Rating, Length: 12782, dtype: object\nCompany Name: Memorial Sloan-Kettering\nLocation: New York, NY\nHeadquarters: New York, NY\nSize: 10000+ employees\nType of ownership: Nonprofit Organization\nIndustry: Health Care Services & Hospitals\nSector: Health Care\nCompetitors: Mayo Clinic, The Johns Hopkins Hospital, MD Anderson Cancer Center"

In [ ]:
df_new3 = pd.DataFrame(df_new2['page_content'])

In [ ]:
df_new3.to_csv('data_jobs.csv', index=False)

In [ ]:
df_new2.to_csv('data_jobs2.csv', index=False)

In [ ]:
#pip install -U chromadb langchain

In [ ]:
import pandas as pd

In [ ]:
df_new3 = pd.read_csv('/content/data_jobs_.csv')

# Import DataFrameLoader
from langchain.document_loaders import DataFrameLoader

# Load the documents from the dataframe into docs
# The page content column is 'movie_description'


docs = DataFrameLoader(
            df_new3,
    page_content_column = 'page_content'
).load()

# Print the first 3 documents and the number of documents
docs[:3]

[Document(page_content="Job Title: Business Analyst - Clinical & Logistics Platform\nSalary Estimate: $56K-$102K \nJob Description: Company Overview\n\n\nAt Memorial Sloan Kettering (MSK), we’re not only changing the way we treat cancer, but also the way the world thinks about it. By working together and pushing forward with innovation and discovery, we’re driving excellence and improving outcomes. For the 28th year, MSK has been named a top hospital for cancer by U.S. News & World Report. We are proud to be on Becker’s Healthcare list as one of the 150 Great Places to Work in Healthcare in 2018, as well as one of Glassdoor’s Employees’ Choice Best Place to Work for 2018. We’re treating cancer, one patient at a time. Join us and make a difference every day.\n\nJob Description\n\n\nWe are excited to recruit two Business Analyst(s) to join our digital, informatics and technology organization who will measure success on our high priority platforms supported by the Division of Health Informatics. DHI focuses on the interaction of people, processes, and technology enabling MSK to meet critical patient care and research objectives. Our division manages a suite of clinical information systems including the electronic health record, ancillary systems and other core components that enable decision support, health information exchange and knowledge management.\n\nAbout the Clinical and Logistics Platform:MSK has committed to transforming itself into a digital organization. To help advance the transformation, MSK has committed to the Scaled Agile Framework (SAFe) as a method of managing technology work. As part of our digital transformation, MSK has identified a set of platforms that it will be creating to advance its digital transformation.\n\nOne of these high priority platforms is the Clinical and Logistics Platform, which is part of MSK’s digital ecosystem. The focus of the Clinical and Logistics Platform is to enable our Care Teams and Health Care Providers with a pre-integrated platform comprising of all our clinical, logistics, and communication systems. We aim to provide a world-class user experience, reduce friction and burnout to our Care Teams, and empower the Care Team members to provide the best patient experience.\n\nYou will:\nSupport agile team in translating end user requirements into set of user product criteria for technical development team & developing documentation\nConnect with team to confirm product commitments\nConduct data analysis and research required for development team to make decisions\nCollaborate with team to understand, analyze, document, and communicate platform requirements\nPartner with key stakeholders to articulate and refine product vision throughout the iteration process\nHelp design team in translating product needs/requirements into deliverable units of work\nAble to synthesize metrics such as: user satisfaction/adoption, quality of products delivered, time-to-market, timely delivery etc.\nCollaborates closely with agile teams to translate business requirements and operational metrics between user groups and developers\nProvide definitions for product criteria, readiness, completeness etc.\nYou have:\n2-4 years of experience in a healthcare setting in a role such as data/business analysis\nBachelor's degree in Health Informatics, Computer Science, Information Systems or related\nSAFe certification or exposure to agile methodologies a strong plus\nStrong problem-solving and analytical skills, with ability to synthesize user needs and pull insights out of data\nExcellent communicator able to negotiate with business to clarify needs vs. wants/likes to balance with development cost and risk\nAbility to break down and describe business needs into work supporting an iterative and incremental delivery model\nCredibility with both business leaders, product designers, & developers\n#LI-POST\n\nBenefits\n\nCompetitive compensation packages | Sick Time | Generous Vacation + 12 holidays to recharge & refuel | Internal Career Mobility & Performance Consulting | Medical, Dental, Vision, FSA & Dependent Care | 403b retirement savings plan match | Tuition Reimbursement | Parental Leave & Adoption Assistance | Commuter Spending Account | Fitness Discounts & Wellness Program | Resource Networks | Life Insurance & Disability | Remote Flexibility\n\nWe believe in communication, transparency, and thinking beyond your 8-hour day @ MSK. It’s important to us that you have a sense of impact, community, and work/life balance to be and feel your best.\n\nOur Hiring Process\n\nYou read the ad, agree it sounds like a great fit & apply -> Talent Acquisition contacts you to schedule a phone interview (if your profile aligns)-> after speaking with the Talent Acquisition Specialist, you will connect with the Hiring Manager by phone or video call -> if your experience is a fit, you will move forward to an on-site visit or video call with the team -> post interview feedback -> ideally an offer! -> reference check & onboarding -> orientation & official welcome to MSK\n\nMSK has been named a Best Place to Work in IT by Insider Pro & Computerworld, for the 2nd year in a row.\n\nWe look forward to meeting soon!\n\nClosing\n\n\nMSK is an equal opportunity and affirmative action employer committed to diversity and inclusion in all aspects of recruiting and employment. All qualified individuals are encouraged to apply and will receive consideration without regard to race, color, gender, gender identity or expression, sexual orientation, national origin, age, religion, creed, disability, veteran status or any other factor which cannot lawfully be used as a basis for an employment decision.\n\nFederal law requires employers to provide reasonable accommodation to qualified individuals with disabilities. Please tell us if you require a reasonable accommodation to apply for a job or to perform your job. Examples of reasonable accommodation include making a change to the application process or work procedures, providing documents in an alternate format, using a sign language interpreter, or using specialized equipment.\nRating: 0        3.9\n1        3.8\n2        3.6\n3        3.6\n4        3.4\n        ... \n12777    4.4\n12778    5.0\n12779    3.8\n12780    4.0\n12781    3.7\nName: Rating, Length: 12782, dtype: object\nCompany Name: Memorial Sloan-Kettering\nLocation: New York, NY\nHeadquarters: New York, NY\nSize: 10000+ employees\nType of ownership: Nonprofit Organization\nIndustry: Health Care Services & Hospitals\nSector: Health Care\nCompetitors: Mayo Clinic, The Johns Hopkins Hospital, MD Anderson Cancer Center"),
 Document(page_content='Job Title: Business Analyst\nSalary Estimate: $56K-$102K \nJob Description: We are seeking for an energetic and collaborative analyst with experience and passion to fill our Business Analyst position. In this role you will be responsible for leading our Data & Analytics function. This is a cross-functional role where you will work with various areas (Investor Relations, Portfolio Excellence, Human Resource and Business Development) collecting and analyzing financial and operational data of our Private Equity and Portfolio Companies. If you enjoy working in a highly collaborative, analytical, fast-paced and dynamic environment, this is the right opportunity for you!\nThe ideal candidate will be highly skilled in all aspects of data analytics, including mining, generation and visualization. The role is committed to transforming data into readable, goal-driven reports for investors and business leaders.\nPosition Summary\nEssential Job Functions:\nTo be the ‘data master’ for key IT platforms that collect financial, operating and contact management data across the portfolio of companies that Paine Schwartz owns and network of contacts\nResponsible for the timeliness and integrity of data in CRM (Salesforce.com) and finance/operating data systems (iLevel) and likely other data in the future\nActively participate in innovative projects to improve the Data Quality or master Data Management within the Firm’s data ecosystem\nResponsible for assisting with the maintenance and updating of core firm marketing material, as well as supporting the Investor Relations & Business Development functions on specific presentation workstreams\nWill support the Human Capital, Investor Relations, Business Development and Portfolio Operations function with insightful and useful reporting and analysis from these systems\nWill have a career path in the exciting Private Equity industry with options to progress into more Financial or other functional responsibilities\nCandidate Requirement\nRequired Skills:\nExcellent excel, database and PPT skills\nUnderstanding of income statements, balance sheets and cash flow reports and how they tie together\nGood people management skills, ability to follow-up and ensure data is received timely and correctly in a professional manner\nExtreme attention to detail\nAbility to take initiative and work independently, while demonstrating strong teamwork\nMust be able to work in a fast-paced environment, manage time and priorities under pressure and meet deadlines\nSpecific Technology platform requirements:\nSalesforce.com (experience with this specific CRM tool is heavily desired):\nCreate custom objects, design page layouts, adjust fields and create custom reports.\nAbility to use Salesforce data loader and Conga reporting solutions\nUnderstanding of Pardot or other email marketing software\nILEVEL (we don’t require experience with this specific portal/finance tool but experience with ERP and financial platforms is desired). Ability to map data from financial statements.\nQualifications:\nUndergraduate degree, preferably finance, economics, business or accounting related\nMinimum two years of experience in a professional business context involving data management, analysis and reporting\nRating: 0        3.9\n1        3.8\n2        3.6\n3        3.6\n4        3.4\n        ... \n12777    4.4\n12778    5.0\n12779    3.8\n12780    4.0\n12781    3.7\nName: Rating, Length: 12782, dtype: object\nCompany Name: Paine Schwartz Partners\nLocation: New York, NY\nHeadquarters: New York, NY\nSize: 1 to 50 employees\nType of ownership: Company - Private\nIndustry: Venture Capital & Private Equity\nSector: Finance\nCompetitors: -1'),
 Document(page_content="Job Title: Data Analyst\nSalary Estimate: $56K-$102K \nJob Description: For more than a decade, Asembia has been working with specialty pharmacies, manufacturers, prescribers, payers and other industry stakeholders to develop solutions for the high-touch specialty pharmaceutical service model.Through collaborative programs, contracting initiatives, patient support hub services and innovative technology platforms, Asembia is committed to positively impacting the patient journey.\n\nAsembia focuses on the specialty pharmacy segment and offers comprehensive hub services, pharmacy network management, group purchasing (GPO) services, innovative technology platforms and more.As a leading industry voice and advocate, Asembia is committed to bringing strategic channel management solutions, leading-edge products and high-touch services to the specialty pharmacy industry that help our customers optimize patient care and outcomes.\n\nPrimary Function:\n\nThe Technical Analystis responsible for implementing data solutions for varied data reporting needs and act as a Subject Matter Expert (SME) for technical data product offerings.\n\nJob Scope and Major Responsibilities:\n\n·Follow all policies and internal processes to ensure data programs and files are delivered in accordance with the provisions of the Health Insurance Portability and Accountability Act of 1996 and its implementing regulations, as amended (“HIPAA”).\n\n·Design, develop and validate data reporting solutions with minimum supervision\n\n·Evaluate data and report findings for accuracy, completeness, per the data specifications.\n\n·Responsible for monitoring file/data receipt per expected schedules. Identify/escalate/ resolve nonconformances.\n\n·Meet data reporting schedules to external stakeholders/ parties for designated data programs.\n\n·Seek and adopt best practices in data reporting, make recommendations for data processing improvements. Identify opportunities to improve the process and data accuracy.\n\n·Provide ad hoc data analysis to internal and external parties as requested.\n\n· Successful collaboration with other Asembia team members to attain a common goal.\n\nQualifications:\n\n·Bachelor’s Degree required. B.A./B.S. Information Systems or similar field preferred.\n\n·Minimum 1 to 3 years of experience working in data analytics or Software Quality assurance – preference towards Prescription / pharmaceutical data.\n\n·Must have a working knowledge of SQL.\n\n·Advance level skills in developing solutions using SQL and SSIS preferred, not required.\n\n·Must be detail oriented with the ability focus on complex processing steps.\n\n·Proven track record with taking ownership in data analytics or Software QA analysis.\n\n·Ability to manage multiple initiatives in a fast paced, dynamic environment.\n\n·Strong self-starter with a sense of ownership.\n\n·Excellent organizational and collaboration skills.\n\nAsembia is committed to Equal Employment Opportunity (EEO) and to compliance with all Federal, State and local laws that prohibit employment discrimination on the basis of race, color, age, natural origin, ethnicity, religion, gender, pregnancy, marital status, sexual orientation, gender identity and expression, citizenship, genetic disposition, disability or veteran's status or any other classification protected by State/Federal laws.\nRating: 0        3.9\n1        3.8\n2        3.6\n3        3.6\n4        3.4\n        ... \n12777    4.4\n12778    5.0\n12779    3.8\n12780    4.0\n12781    3.7\nName: Rating, Length: 12782, dtype: object\nCompany Name: Asembia\nLocation: Florham Park, NJ\nHeadquarters: Florham Park, NJ\nSize: 501 to 1000 employees\nType of ownership: Company - Private\nIndustry: Biotech & Pharmaceuticals\nSector: Biotech & Pharmaceuticals\nCompetitors: -1")]

In [ ]:
#pip install tiktoken==0.5.1

In [ ]:
# Import tiktoken
import tiktoken

# Create the encoder
encoder = tiktoken.get_encoding("cl100k_base")

# Create a list containing the number of tokens for each document
tokens_per_docs = [len(encoder.encode(doc.page_content)) for doc in docs]

#tokens_per_docs
# Show the estimated cost, which is the sum of the amount of tokens divided by 1000, times $0.0001
total_tokens = sum(tokens_per_docs)
cost_per_1000_tokens = 0.0001
cost = (total_tokens / 1000) * cost_per_1000_tokens
cost

ModuleNotFoundError: No module named 'tiktoken'

In [ ]:
# from chromadb.utils import embedding_functions
# default_ef = embedding_functions.DefaultEmbeddingFunction()
# sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

In [ ]:
#pip install sentence_transformers

In [ ]:
from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [ ]:
from langchain_community.document_loaders import TextLoader
from langchain_community.embeddings.sentence_transformer import (
    SentenceTransformerEmbeddings,
)
from langchain_community.vectorstores import Chroma
from langchain_text_splitters import CharacterTextSplitter

In [ ]:
#import chromadb

In [ ]:
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(docs)

In [ ]:
# create the open-source embedding function
embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:


# load it into Chroma
db = Chroma.from_documents(docs, embedding_function,persist_directory='./chroma_db_')

In [ ]:
# persiste the db to disk
db.persist()
#vectordb= None

In [ ]:
import zipfile
import os

def zip_directory(directory_path, output_filename):
    with zipfile.ZipFile(output_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(directory_path):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, directory_path)
                zipf.write(file_path, arcname)

# Usage
chroma_db_path = "./chroma_db_"  # Replace with your Chroma DB directory path
output_zip = "chroma_db_compressed_.zip"
zip_directory(chroma_db_path, output_zip)

In [ ]:
from google.colab import files

# Replace 'filename.txt' with the name of your file
files.download('/content/chroma_db_compressed_.zip')

In [ ]:
# Step 1: Decompress the zip file
zip_file_path = "chroma_db_compressed_.zip"
extract_path = "./chroma_db_extracted"

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

NameError: name 'embedding_function' is not defined

In [ ]:
  # Step 3: Load the Chroma database from the extracted directory
loaded_vectorstore = Chroma(
    persist_directory=extract_path,
    embedding_function=embedding_function
)

In [ ]:
vectordb= None

In [ ]:
# Now we can load the persisted database from disk, and use it as normal.
vectordb = Chroma(persist_directory=vectordb,
                  embedding_function=embedding_function)

SyntaxError: keyword argument repeated: persist_directory (<ipython-input-24-64547087161a>, line 3)

In [ ]:
loaded_vectorstore

In [ ]:
retriever = db.as_retriever()
docs = retriever.get_relevant_documents(query)

In [ ]:
# query it
query = "Recommed a company to work as a data scientist in the health sector"
docs = loaded_vectorstore.similarity_search(query, k=1)

# print results
print(docs[0].page_content)

Job Title: Data Scientist
Salary Estimate: $76K-$122K
Job Description: Join a thriving company that is changing the way cancer care is delivered for millions of patients around the country. Recently spun off from an internationally renowned research and treatment hospital, AccessHope understands that cancer doesn’t play by the rules, so we don’t either. We are an agile innovative brand that’s backed by a founding member of the National Cancer Center Network. Now, we’re joining forces with employers to bring state-of-the-art cancer expertise to their employees and give patients access to the latest developments in precision medicine, genetic risk assessment and clinical trials, regardless of where they live. The goal? To dramatically improve care, outcomes and value during cancer treatment.

It’s a revolutionary new model – and we’re looking for revolutionary thinkers to join us.

A data scientist is someone who knows how to extract meaning from and interpret data, which requires both tools and methods from statistics and machine learning, as well as being human.

Role & Responsibility

The Data Scientist is responsible for advising the business on the potential of data, to provide new insights into the business's mission, and through the use of advanced statistical analysis, data mining, and data visualization techniques, to create solutions that enable enhanced business performance.

The Data Scientist functions include:
Undertaking data collection, pre-processing and analysis
Building models to address business problems
Presenting information using data visualization techniques
Identify valuable data sources and automate collection processes
Analyze large amounts of information to discover trends and patterns
Skills
Programming
Statistics
Data Wrangling
Data Visualization & Communication
Data Intuition
Machine Learning (algorithms
Requirements
Minimum 3 years’ experience as a Data Scientist or Data Analyst
Experience in data mining
Understanding of machine-learning and operations research
Knowledge of R, SQL and Python; familiarity with Scala, Java or C++ is an asset
Experience with in-depth rate development templates, risk score analyses, trend analyses, cost management/financial initiatives, back-end technical development and programming
Experience using business intelligence tools (e.g. Tableau, Power BI) and data frameworks (e.g. Hadoop)
Analytical mind and business acumen
Problem-solving aptitude
Excellent communication and presentation skills
BSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred
Healthcare experience a plus, but not required.
Education
BSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred
Healthcare experience a plus, but not required.
Rating: 0        3.9
1        3.8
2        3.6
3        3.6
4        3.4
        ...
12777    4.4
12778    5.0
12779    3.8
12780    4.0
12781    3.7
Name: Rating, Length: 12782, dtype: object
Company Name: AccessHope
Location: Irwindale, CA
Headquarters: -1
Size: -1
Type of ownership: -1
Industry: -1
Sector: -1
Competitors: -1

In [ ]:
# query it
query = "Recommed a company to work as a data scientist in the health sector"
docs = vectordb.similarity_search(query, k=1)

# print results
print(docs[:2])

[Document(page_content="Job Title: Data Scientist\nSalary Estimate: $76K-$122K \nJob Description: Join a thriving company that is changing the way cancer care is delivered for millions of patients around the country. Recently spun off from an internationally renowned research and treatment hospital, AccessHope understands that cancer doesn’t play by the rules, so we don’t either. We are an agile innovative brand that’s backed by a founding member of the National Cancer Center Network. Now, we’re joining forces with employers to bring state-of-the-art cancer expertise to their employees and give patients access to the latest developments in precision medicine, genetic risk assessment and clinical trials, regardless of where they live. The goal? To dramatically improve care, outcomes and value during cancer treatment.\n\nIt’s a revolutionary new model – and we’re looking for revolutionary thinkers to join us.\n\nA data scientist is someone who knows how to extract meaning from and interpret data, which requires both tools and methods from statistics and machine learning, as well as being human.\n\nRole & Responsibility\n\nThe Data Scientist is responsible for advising the business on the potential of data, to provide new insights into the business's mission, and through the use of advanced statistical analysis, data mining, and data visualization techniques, to create solutions that enable enhanced business performance.\n\nThe Data Scientist functions include:\nUndertaking data collection, pre-processing and analysis\nBuilding models to address business problems\nPresenting information using data visualization techniques\nIdentify valuable data sources and automate collection processes\nAnalyze large amounts of information to discover trends and patterns\nSkills\nProgramming\nStatistics\nData Wrangling\nData Visualization & Communication\nData Intuition\nMachine Learning (algorithms\nRequirements\nMinimum 3 years’ experience as a Data Scientist or Data Analyst\nExperience in data mining\nUnderstanding of machine-learning and operations research\nKnowledge of R, SQL and Python; familiarity with Scala, Java or C++ is an asset\nExperience with in-depth rate development templates, risk score analyses, trend analyses, cost management/financial initiatives, back-end technical development and programming\nExperience using business intelligence tools (e.g. Tableau, Power BI) and data frameworks (e.g. Hadoop)\nAnalytical mind and business acumen\nProblem-solving aptitude\nExcellent communication and presentation skills\nBSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred\nHealthcare experience a plus, but not required.\nEducation\nBSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred\nHealthcare experience a plus, but not required.\nRating: 0        3.9\n1        3.8\n2        3.6\n3        3.6\n4        3.4\n        ... \n12777    4.4\n12778    5.0\n12779    3.8\n12780    4.0\n12781    3.7\nName: Rating, Length: 12782, dtype: object\nCompany Name: AccessHope\nLocation: Irwindale, CA\nHeadquarters: -1\nSize: -1\nType of ownership: -1\nIndustry: -1\nSector: -1\nCompetitors: -1")]

In [ ]:
docs

[]

In [ ]:
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_openai import ChatOpenAI

#chat = ChatOpenAI(temperature=0)
from google.colab import userdata
openai_api_key = userdata.get('OPENAI_API_KEY')

chat = ChatOpenAI(model_name="gpt-3.5-turbo", openai_api_key=openai_api_key)

In [ ]:
messages = [
    SystemMessage(content="You are a helpful assistant."),
    HumanMessage(content="Hi AI, how are you today?"),
    #ChatPromptTemplate(content="I'm great thank you. How can I help you?"),
    HumanMessage(content="I'd like to understand string theory.")
]

In [ ]:
res = chat(messages)

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(

In [ ]:
res.content

'String theory is a theoretical framework in physics that attempts to explain the fundamental nature of particles and forces in the universe. It proposes that the most basic building blocks of the universe are not point-like particles, as traditionally thought, but rather tiny, vibrating strings. These strings can vibrate at different frequencies, giving rise to different particles and forces.\n\nString theory is still a very active area of research in theoretical physics and has the potential to unify our understanding of the four fundamental forces of nature: gravity, electromagnetism, the weak nuclear force, and the strong nuclear force. However, it is a complex and mathematically demanding theory that has yet to be experimentally confirmed.\n\nIf you have any specific questions about string theory or would like to learn more about a particular aspect of it, feel free to ask!'

In [ ]:
def augment_prompt(query: str):
    results = loaded_vectorstore.similarity_search(query, k=3)
    source_knowledge = "\n".join([x.page_content for x in results])
    augmented_prompt = f"""Using the contexts below, answer the query. If some information is not provided within
the contexts below, do not include, and if the query cannot be answered with the below information, say "I don't know".

Contexts:
{source_knowledge}

Query: {query}"""
    return augmented_prompt

In [ ]:
print(augment_prompt(query))

Using the contexts below, answer the query. If some information is not provided within
the contexts below, do not include, and if the query cannot be answered with the below information, say "I don't know".

Contexts:
Job Title: Data Scientist
Salary Estimate: $76K-$122K
Job Description: Join a thriving company that is changing the way cancer care is delivered for millions of patients around the country. Recently spun off from an internationally renowned research and treatment hospital, AccessHope understands that cancer doesn’t play by the rules, so we don’t either. We are an agile innovative brand that’s backed by a founding member of the National Cancer Center Network. Now, we’re joining forces with employers to bring state-of-the-art cancer expertise to their employees and give patients access to the latest developments in precision medicine, genetic risk assessment and clinical trials, regardless of where they live. The goal? To dramatically improve care, outcomes and value during cancer treatment.

It’s a revolutionary new model – and we’re looking for revolutionary thinkers to join us.

A data scientist is someone who knows how to extract meaning from and interpret data, which requires both tools and methods from statistics and machine learning, as well as being human.

Role & Responsibility

The Data Scientist is responsible for advising the business on the potential of data, to provide new insights into the business's mission, and through the use of advanced statistical analysis, data mining, and data visualization techniques, to create solutions that enable enhanced business performance.

The Data Scientist functions include:
Undertaking data collection, pre-processing and analysis
Building models to address business problems
Presenting information using data visualization techniques
Identify valuable data sources and automate collection processes
Analyze large amounts of information to discover trends and patterns
Skills
Programming
Statistics
Data Wrangling
Data Visualization & Communication
Data Intuition
Machine Learning (algorithms
Requirements
Minimum 3 years’ experience as a Data Scientist or Data Analyst
Experience in data mining
Understanding of machine-learning and operations research
Knowledge of R, SQL and Python; familiarity with Scala, Java or C++ is an asset
Experience with in-depth rate development templates, risk score analyses, trend analyses, cost management/financial initiatives, back-end technical development and programming
Experience using business intelligence tools (e.g. Tableau, Power BI) and data frameworks (e.g. Hadoop)
Analytical mind and business acumen
Problem-solving aptitude
Excellent communication and presentation skills
BSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred
Healthcare experience a plus, but not required.
Education
BSc/BA in Computer Science, Engineering or relevant field; graduate degree in Data Science or other quantitative field is preferred
Healthcare experience a plus, but not required.
Rating: 0        3.9
1        3.8
2        3.6
3        3.6
4        3.4
        ...
12777    4.4
12778    5.0
12779    3.8
12780    4.0
12781    3.7
Name: Rating, Length: 12782, dtype: object
Company Name: AccessHope
Location: Irwindale, CA
Headquarters: -1
Size: -1
Type of ownership: -1
Industry: -1
Sector: -1
Competitors: -1
Job Title: Data Scientist
Salary Estimate: $113K-$180K
Job Description: OverviewWelcome to Allscripts! Our Mission is to be the most trusted provider of innovative solutions that empower all stakeholders across the healthcare continuum to deliver world-class outcomes. Our Vision is a Connected Community of Health that spans continents and borders. With the largest community of clients in healthcare, Allscripts is able to deliver an integrated platform of clinical, financial, connectivity and information solutions to facilitate enhanced collaboration and exchange of critical patient information.

The primary purpose of the Data Scientist role is to conduct analytics research that leads to improved health outcomes across PIH Health in Whittier, CA. The Data Scientist will be responsible for enterprise-wide data analysis, scorecards and dashboard development and reporting solutions.This will role will consist of daily operational tasks and project based activities.

Responsibilities

• Conducts analytical research based on project assigned that leads to new or improved products to maintain Allscripts competitive position.
• Under direction of more senior resources, researches emerging technologies to support improved health outcomes
• Performs testing of predictive models on data
• Designs, codes, tests and documents in areas assigned on projects
• Collaborates with SMEs to select relevant sources of information
• Works with teams to support data collection, integration and retention requirements incorporating business knowledge and best practices
• Uses expected qualification and assurance of information to quantify the accuracy of metrics and analysis
• Works to ensure information is used in compliance with regulatory and security policies
• Provides on-going tracking and monitoring of performance decision systems and statistical models

Qualifications

Academic and Professional Qualifications:

• Bachelors or Masters degree in a relevant field of study (health sciences, computer science, engineering or other quantitative)

Experience:

• 2+ years experience in an healthcare analytics role
• Experience with data management
• Experience with pre-processing, cleaning of data
• Knowledge of statistical techniques
• Effectively uses research and cutting edge technology and data to solve problems
• Experience with SQL, SSIS, Tableau and database development
• Demonstrated critical thinking skills and attention to detail
• Excellent client facing skills with the ability to thrive in a highly critical, fast paced environment

Travel Requirements:

• No usual travel
• Travel to educational conferences as needed

Working Arrangements:

• Work is performed in a standard office environment with minimal exposure to health or safety hazards

At Allscripts, our greatest strength comes from bringing together talented people with diverse perspectives to support the technology needs of 180,000 physicians, 1,500 hospitals and 10,000 post-acute organizations across the globe. Allscripts offers a comprehensive compensation and benefits package, including holidays, vacation, medical, dental, and vision insurance, company paid life insurance and retirement savings.

Allscripts policy is to provide equal employment opportunity and affirmative action in all of its employment practices without regard to race, color, religion, sex, national origin, ancestry, marital status, protected veteran status, age, individuals with disabilities, sexual orientation or gender identity or expression or any other legally protected category. Applicants for North American based positions with Allscripts must be legally authorized to work in the United States or Canada. Verification of employment eligibility will be required as a condition of hire.

From a "VEVRAA Federal Contractor" We request Priority Referral of Protected Veterans

This is an official Allscripts Job posting. To avoid identity theft, please only consider applying to jobs posted on our official corporate site.

Job Requirements:
Rating: 0        3.9
1        3.8
2        3.6
3        3.6
4        3.4
        ...
12777    4.4
12778    5.0
12779    3.8
12780    4.0
12781    3.7
Name: Rating, Length: 12782, dtype: object
Company Name: Allscripts
Location: Whittier, CA
Headquarters: Chicago, IL
Size: 5001 to 10000 employees
Type of ownership: Company - Public
Industry: Computer Hardware & Software
Sector: Information Technology
Competitors: Cerner, Epic, Athena Health Care Systems
Job Title: Data Scientist - Social Impact (FT)
Salary Estimate: $146K-$175K
Job Description: Data Scientist - Social Impact (FT)

Req #: 0000049004
Category: Professional / Management
Status: Full-Time
Shift: Day
Facility: RWJBarnabas Health Corporate Services
Location:
Walmart SDOH Grant,

95 Old Short Hills Road, West Orange, NJ 07052

Job Summary:

RWJBarnabas Health (RWJBH) seeks an experienced and innovative Data Scientist to join our team. In an effort to meet its mission of creating healthier communities, RWJBH seeks to effectively and efficiently bridge the health care and social services sector. To this end, the ideal candidate will be intricately involved in working across departments to analyze the multiple datasets, internal and external to the RWJBH System, that address the socioeconomic, behavioral, clinical, and environmental factors that affect health outcomes. This role offers the ideal opportunity for an entrepreneurial thinker to re-engineer and transform siloed systems in an effort to improve the lives of our current and future patients, increase efficiency for our personnel, and create healthier communities.

Essential Functions:
Collaborate with stakeholders throughout the RWJBH to identify opportunities to leverage company data to drive integrated care, process improvements, and business solutions
Assess the effectiveness and accuracy of clinical and social data sources and work with internal stakeholders to develop processes necessary to secure individual-level data from partner entities
Develop custom data models and algorithms, in an effort to match relevant data sources to streamline existing processes, as well as successfully integrate clinical and social datasets
Create predictive and prescriptive modeling to increase and optimize the experience of patients and healthcare personnel, as well as generate the insight required to support changing healthcare financing models and revenue streams
Coordinate across departments to implement models and monitor outcomes
Develop processes and tools to monitor and analyze model performance and data accuracy
Develop standard reporting mechanisms for multiple audiences
Job Requirements:
Advanced degree or equivalent experience in Machine Learning, Statistics, Computer Science, or associated field; multi-sector experience a plus
A minimum of 5-7 years of experience manipulating data sets and building statistical models
A commitment to the mission of RWJBH and dedication to improve health outcomes, promote health equity and eliminate health disparities
Superior written and verbal skills with the ability to translate complex data and concepts into user-friendly information that is relevant across disciplines for diverse stakeholders
Ability to analyze large, diverse datasets and offer thoughtful insight, problem solving, and critical thinking needed to transform processes and outcomes
Experience leading a project from conception to release. Demonstrated ability to help track projects and ensure deliverables/scope are clearly communicated and managed
A drive to learn and master new technologies and techniques, as well as share their relevance and applicability to key stakeholders
Experience using statistical computer languages (R, Python, SLQ, etc.) to manipulate data and draw insights from large data sets
Knowledge of a variety of machine learning techniques (clustering, decision tree learning, artificial neural networks, etc.) and their real-world advantages/drawbacks
Knowledge of advanced statistical techniques and concepts (regression, properties of distributions, statistical tests and proper usage, etc.) and experience with applications
Knowledge and experience in statistical and data mining techniques: GLM/Regression, Random Forest, Boosting, Trees, text mining, social network analysis, etc
Experience querying databases and using statistical computer languages: R, Python, SLQ, etc
Experience using web services: Redshift, S3, Spark, DigitalOcean, etc
Experience creating and using advanced machine learning algorithms and statistics: regression, simulation, scenario analysis, modeling, clustering, decision trees, neural networks, etc.
Experience analyzing data from 3rd party providers, including but not limited to government agencies, Google Analytics, Site Catalyst, Coremetrics, Adwords, Crimson Hexagon, Facebook Insights, etc
Experience with distributed data/computing tools: Map/Reduce, Hadoop, Hive, Spark, Gurobi, MySQL, etc
Experience visualizing/presenting data for stakeholders using: Periscope, Business Objects, D3, ggplot, etc
Other Duties:

Please note this job description is not designed to cover or contain a comprehensive listing of activities, duties or responsibilities that are required of the employee for this job. Duties, responsibilities and activities may change at any time with or without notice.

Additional Information:
We offer a great work environment, competitive rates and excellent benefits, including:
Medical/Dental/Vision plans
401 (k)
Vacation/Personal/Holiday/Sick Time Off
Short & Long Term Disability
Basic Life & Accidental Death Insurance
Tuition Reimbursement
Health Care/Dependent Care Flexible Spending Accounts
RWJBarnabas Health is the most comprehensive health care delivery system in New Jersey and the state s second largest private employer with more than 32,000 employees, 9,000 physicians and 1,000 residents and interns. The system includes eleven acute care hospitals, three acute care children s hospitals and a leading pediatric rehabilitation hospital (Children s Specialized Hospital).

RWJBarnabas Health is an Equal Opportunity Employer
Rating: 0        3.9
1        3.8
2        3.6
3        3.6
4        3.4
        ...
12777    4.4
12778    5.0
12779    3.8
12780    4.0
12781    3.7
Name: Rating, Length: 12782, dtype: object
Company Name: Barnabas Health
Location: West Orange, NJ
Headquarters: Gibsonia, PA
Size: 501 to 1000 employees
Type of ownership: Company - Public
Industry: -1
Sector: -1
Competitors: -1

Query: Recommed a company to work as a data scientist in the health sector

In [ ]:
prompt = HumanMessage(content=augment_prompt(query))

messages.append(prompt)
res = chat(messages)
print(res.content)

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `BaseChatModel.__call__` was deprecated in langchain-core 0.1.7 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(

Based on the provided contexts, I recommend considering Allscripts as a company to work as a data scientist in the health sector. Allscripts is a prominent healthcare technology company based in Whittier, CA, with headquarters in Chicago, IL. They offer a comprehensive platform of clinical, financial, connectivity, and information solutions to enhance collaboration and critical patient information exchange. The company values diversity and equal employment opportunities. With a strong focus on utilizing data to drive integrated care and improve health outcomes, Allscripts provides an innovative and dynamic environment for data scientists in the healthcare sector.

In [ ]:
prompt = HumanMessage(content=augment_prompt("what are the job responsibilities of product data analysts in health sectors"))

messages.append(prompt)
res = chat(messages)
print(res.content)

Based on the provided job descriptions, the job responsibilities of Product Data Analysts in the health sector typically include:

1. Conducting complex research, analysis, and reporting to support Quality Improvement data needs.
2. Collecting, analyzing, and synthesizing data to guide business decision-making for health management, cost of healthcare management, and quality of care.
3. Assisting in tracking data files, generating reports, and supporting program applications to meet State and Federal mandates.
4. Improving patient care, care coordination, efficiency, and quality while ensuring compliance standards are met.
5. Developing technical specifications and executing work plans for analyses.
6. Designing and developing analytic reports and data visualizations.
7. Understanding and analyzing healthcare claims data to identify trends and patterns.
8. Interpreting data analysis results and presenting conclusions to internal teams.
9. Working with statistical analytical toolsets to produce database tables, statistical results, and graphical representations.
10. Building and automating custom data processes using workflow tools.
11. Translating business needs into data-driven deliverables and analyses.
12. Creating, merging, and querying large datasets.
13. Providing recommendations on methods to obtain and analyze data to improve data systems' quality and efficiency.
14. Communicating effectively with stakeholders to identify reporting needs and create reports.
15. Ensuring data integrity and quality assurance before delivering results.
16. Training end users on new reports and dashboards.

These responsibilities focus on utilizing data analysis to drive informed decision-making, improve healthcare outcomes, and streamline processes within the health sector.

In [ ]:
for message in messages:
    message.content = message.content[:1000]

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")

tokenizer_config.json:   0%|          | 0.00/2.16k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/888 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/13.5k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/67.1M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

In [ ]:
len(augment_prompt("what are the job responsibilities of product data analysts in health sectors"))

NameError: name 'augment_prompt' is not defined

In [ ]:
input_text =augment_prompt("what are the job responsibilities of product data analysts in health sectors")
input_ids = tokenizer(input_text, return_tensors="pt")

outputs = model.generate(**input_ids,max_new_tokens=1967)
print(tokenizer.decode(outputs[0]))

In [ ]:
# Function to perform web search
def perform_web_search(query):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"}
    search_results = ""

    # Glassdoor search
    glassdoor_url = f"https://www.glassdoor.com/Search/results.htm?keyword={query}"
    response = requests.get(glassdoor_url, headers=headers)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        glassdoor_results = soup.find_all('div', {'class': 'jobContainer'})
        for result in glassdoor_results[:5]:  # limiting to first 3 results
            title = result.find('a', {'class': 'jobInfoItem jobTitle'}).text.strip() if result.find('a', {'class': 'jobInfoItem jobTitle'}) else 'N/A'
            company = result.find('div', {'class': 'jobInfoItem jobEmpolyerName'}).text.strip() if result.find('div', {'class': 'jobInfoItem jobEmpolyerName'}) else 'N/A'
            location = result.find('span', {'class': 'subtle loc'}).text.strip() if result.find('span', {'class': 'subtle loc'}) else 'N/A'
            search_results += f"Glassdoor Result: {title} at {company}, {location}\n"

    # Indeed search
    indeed_url = f"https://www.indeed.com/jobs?q={query}&limit=10"
    response = requests.get(indeed_url, headers=headers)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        indeed_results = soup.find_all('div', {'class': 'jobsearch-SerpJobCard'})
        for result in indeed_results[:5]:  # limiting to first 3 results
            title = result.find('h2', {'class': 'title'}).text.strip() if result.find('h2', {'class': 'title'}) else 'N/A'
            company = result.find('span', {'class': 'company'}).text.strip() if result.find('span', {'class': 'company'}) else 'N/A'
            location = result.find('span', {'class': 'location'}).text.strip() if result.find('span', {'class': 'location'}) else 'N/A'
            search_results += f"Indeed Result: {title} at {company}, {location}\n"

    return search_results

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
results = perform_web_search("data scientist")

In [ ]:
results

''